name: Papaya
settings:
  DEVELOPMENT_TEAM: T7PP2KY2B6
packages:
  SwiftCollections:
    url: https://github.com/apple/swift-collections 
    from: 1.3.0

targets:
  Papaya:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 18.0
    sources: 
      - path: Papaya
    scheme: {}
    dependencies:
      - package: SwiftCollections
        product: Collections

    info:
      path: Papaya/Supporting/Info.plist
      properties:
        CFBundleDisplayName: $(PRODUCT_NAME)
        CFBundleLocalizations: [ en ]
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        ITSAppUsesNonExemptEncryption: NO
        UILaunchScreen:
          UIViewControllerBasedStatusBarAppearance: false
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_NAME: $(TARGET_NAME)
      INFOPLIST_FILE: Papaya/Supporting/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: de.tum.cit.ase.ios25.Papaya
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 1
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    postCompileScripts:
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        script: |-
          if [[ "${CONFIGURATION}" = Release ]]; then
            # Do not extra lint in CI
            exit 0
          fi

          if [[ "$(uname -m)" == arm64 ]]; then
              export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
              swiftlint
          else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
